### ISSUE TITLE
Correction et amélioration de l'appli

### ISSUE THREAD

**Issue by chronoss09** [PoloNX/sigpatch-downloader#2]
![2021061002370700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17669980/121481698-b01af480-c9cc-11eb-92b3-f225556caf45.jpg)

- Ajout d'une détection de connexion internet sur la console avec message d'erreur si console pas connectée sur internet
- Ajout d'un message d'erreur si échec de téléchargement des sigpatch
- Remplacement de "Hekate" par "Reboot" sur la fenêtre de fin de téléchargement après le téléchargement des sigpatch

**Comment by PoloNX** [comment]
> ![2021061002370700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17669980/121481698-b01af480-c9cc-11eb-92b3-f225556caf45.jpg)
> 
> 
> 
> - Ajout d'une détection de connexion internet sur la console avec message d'erreur si console pas connectée sur internet
> 
> - Ajout d'un message d'erreur si échec de téléchargement des sigpatch
> 
> - Remplacement de "Hekate" par "Reboot" sur la fenêtre de fin de téléchargement après le téléchargement des sigpatch

Hi friend, I will add these features for the 1.2.0

**Comment by PoloNX** [comment]
Finish, I will release this later
